
import "./globals.css";


export const metadata = {
  title: "Dokan",
  description: "Generated by create next app",
  keywords:"online shopping ,e-commerce,buy and sell"
};

export default function RootLayout({ children }) {
  return (
    <html lang="ne">
      <body> 
<header className="shadow shadow-white ">
<div className="container px-5 mx-auto py-2">
  <div className="flex space-x-3 justify-between items-center">
    <h1 className="text-2xl bold">Ghar Sau</h1>
<nav>
  <ul className="flex space-x-4">
    <li><a href="/">Home</a></li>
    <li><a href="/contact">Contact</a></li>
    <li><a href="/login">Login</a></li>
    <li><a href="/register">Register</a></li>
    <li><a href="/products">Products</a></li>
    <li><a href="/prodd">Products</a></li>

  </ul>
</nav>
  </div>
</div>
</header>






        {children}
   
<footer>ths is the footer</footer>
      </body>
    </html>
  );
}
