import Link from "next/link";
import "./globals.css";
import config from "@/config";
import Header from "@/components/Header";
import Footer from "@/components/Footer";



export const metadata = {
  title: {
   default:config.appName,
    template:`${config.appName}-%s`
  },
  description: "Generated by create next app",
  keywords: "online shopping ,e-commerce,buy and sell",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ne">
      <body>
<Header/>

        {/* children */}
<main className="min-h-svh">

        {children}
</main>

        {/* footer  */}
<Footer/>
      </body>
    </html>
  );
}
